### ISSUE TITLE
fails on character creation when type = 0 / kbiped

### ISSUE THREAD

**Issue by Klockbox** [janberger/aniMeta#7]
When using either the Create New Character Button, or the button from the menu create -> Biped I get the following error:

> aniMeta: Build Skeleton.
>  Traceback (most recent call last):
>    File "C:/Program Files/Autodesk/Maya2023/bin/plug-ins/aniMeta.py", line 5078, in create
>      self.build_skeleton( skeleton, rootNode )
>    File "C:/Program Files/Autodesk/Maya2023/bin/plug-ins/aniMeta.py", line 1394, in build_skeleton
>      self.create_blend_joints()
>    File "C:/Program Files/Autodesk/Maya2023/bin/plug-ins/aniMeta.py", line 1425, in create_blend_joints
>      parent = mc.listRelatives(joint, parent=True)[0]
>  ValueError: No object matches name: upperarm_l

As far as I understand the issue it seems to look for the UE Biped joint names that are defined on line 1412 onwards, instead of the kBiped joint names.
> joints = [ 'upperarm_', 'lowerarm_', 'hand_',
>                    'thumb_01_', 'thumb_02_', 'thumb_03_',
>                    'index_01_', 'index_02_', 'index_03_',
>                    'middle_01_', 'middle_02_', 'middle_03_',
>                    'ring_01_', 'ring_02_', 'ring_03_',
>                    'pinky_01_', 'pinky_02_', 'pinky_03_',
>                    'thigh_', 'calf_', 'foot_', 'ball_'
>                    ]

BipedUE creation works fine, as far as I can tell.

I am using Maya 2023.

**Comment by Klockbox** [comment]
Further testing yielded the following results:
Maya 2023 and onwards seem to have an issue with pymel on my current machine, but that mostly guessworking. This triggers errors when loading some older versions of animeta.
Commit "works now with Z axis up" and maya 2022.5.1 can create a kbiped rig without issue.
On maya 2022.5.1, issues start from commit "Improved Z-Up mode". Error is:

> Traceback (most recent call last):
>    File "C:/Program Files/Autodesk/Maya2022/bin/plug-ins/aniMeta.py", line 5093, in create
>      self.build_body_guides( rootNode, type )
>    File "C:/Program Files/Autodesk/Maya2022/bin/plug-ins/aniMeta.py", line 3914, in build_body_guides
>      mc.setAttr( 'Clavicle_Rgt_Guide_Grp.offsetParentMatrix', m, typ='matrix' )
>  RuntimeError: setAttr: No object matches name: Clavicle_Rgt_Guide_Grp.offsetParentMatrix
